# Generated by Django 4.0.1 on 2022-01-19 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='zoommeetings',
            table='zoom_meetings',
        ),
        migrations.AlterModelTable(
            name='zoomusers',
            table='zoom_users',
        ),
    ]
