# Generated by Django 4.0.1 on 2022-01-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_manager', '0002_alter_zoommeetings_table_alter_zoomusers_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoomCredentionals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_data', models.CharField(max_length=255)),
                ('data', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'zoom_credentionals',
            },
        ),
    ]
