# Generated by Django 4.0.1 on 2022-01-31 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_manager', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
